### ISSUE TITLE
No names for Start and End Points for Below BesserMitFahren Trip

### ISSUE THREAD

**Issue by ryildiz** [fahrgemeinschaft/FredEddisonMetaSearch#10]
We don't receive any names for Start and End Points of below BesserMitFahren Trip.

https://www.bessermitfahren.de/berlin/talkau/mitfahrgelegenheit/818055/0/14/1600552800

![image](https://user-images.githubusercontent.com/1078834/93452799-87ece200-f8e1-11ea-8557-84514f59928c.png)

**Comment by merlinro** [comment]
have just added it

**Comment by merlinro** [comment]
added it
