### ISSUE TITLE
Please configure the dependabot so that you get the notifications and fix the mentioned issues

### ISSUE THREAD

**Issue by frankgerhardt** [fahrgemeinschaft/FredEddisonMetaSearch#12]

**Comment by merlinro** [comment]
@frankgerhardt what is the dependabot?

**Comment by frankgerhardt** [comment]
It is configured in this repo to notify about dependency problems. Currently Sven gets these emails but he can't do anything about it. You should get these notifications and not Sven. And better keep dependencies up to date so that there are no notifications at all.
