### ISSUE TITLE
Default value for DepartureTime when it's not available.

### ISSUE THREAD

**Issue by ryildiz** [fahrgemeinschaft/FredEddisonMetaSearch#5]
For the trips having no departure time information, meta-search service provides departure time as 02:00.  
But there is no time information in the Mifatz trip detail. This causes inconsistency from user experience perspective.
 
When departureTime does not exist, it should come from meta-search service as null not with a default time(02:00).

**Comment by merlinro** [comment]
I have just made an update. Please test it once via the GUI.
