### ISSUE TITLE
Result for toleranceInDays=0  and the result for toleranceInDays=2  seem to be exactly same

### ISSUE THREAD

**Issue by ryildiz** [fahrgemeinschaft/FredEddisonMetaSearch#7]
Support for toleranceInDays would be nice.

**Comment by merlinro** [comment]
Can you give an example request here? I have tested it and I cannot reproduce the problem.

`{"startPoint":{"location":{"latitude":52.5198535,"longitude":13.4385964}, "radius": "50.0"},"endPoint":{"location":{"latitude":53.5511,"longitude":9.9937}, "radius": "50.0"},"departure":{"time":"2020-09-10T11:06:04.690Z","toleranceInDays":2},"arrival":null,"page":{"firstIndex":20,"page":0,"pageSize":20},"reoccurDays":null,"availabilityStarts":"2020-09-10T11:06:04.690Z","availabilityEnds":null,"tripTypes":[0],"transportTypes":[0],"animals":2,"baggage":1,"gender":2,"organizations":[],"smoking":3}
`

=>  "total": 14


and 
`{"startPoint":{"location":{"latitude":52.5198535,"longitude":13.4385964}, "radius": "50.0"},"endPoint":{"location":{"latitude":53.5511,"longitude":9.9937}, "radius": "50.0"},"departure":{"time":"2020-09-10T11:06:04.690Z","toleranceInDays":0},"arrival":null,"page":{"firstIndex":20,"page":0,"pageSize":20},"reoccurDays":null,"availabilityStarts":"2020-09-10T11:06:04.690Z","availabilityEnds":null,"tripTypes":[0],"transportTypes":[0],"animals":2,"baggage":1,"gender":2,"organizations":[],"smoking":3}`


=>  "total": 1

And the date fields are also correct
