### ISSUE TITLE
Currency field is missing

### ISSUE THREAD

**Issue by ryildiz** [fahrgemeinschaft/FredEddisonMetaSearch#8]
![image](https://user-images.githubusercontent.com/1078834/92815422-e3dcd580-f3cc-11ea-892d-58a482b05f64.png)

- Price information comes only for Bessermitfahren connector. No price for Mifaz. 
- Currency information does not come for Bessermitfahren connector.

For example: 
https://www.bessermitfahren.de/berlin/sankt-georg1/mitfahrgelegenheit/853958/0/32/1599775200

tripID:
bessermitfahren-8a8ad99e729e0afcd71fdc85fd360386

**Comment by merlinro** [comment]
Hey, at Mifaz there is no info about prices, and at Bessermitfahren there is no info about the currency (I think it is always €) 

Should I always add € as currency ? 


https://api.mifaz.de/Mifaz-GET-Spezifikation.html

https://www.bessermitfahren.de/api
 (unfortunately only in german)

**Comment by ryildiz** [comment]
Here in "Preis" field:
https://www.bessermitfahren.de/berlin/sankt-georg1/mitfahrgelegenheit/853958/0/32/1599775200

there is "Preis:~ 10,00 € pro Person"  maybe we can extract it from text if it's coming.

In UI I put default value as €. I think no need to put a default value in the backend. But if you can extract it, it would be better maybe.

**Comment by merlinro** [comment]
in the api we only get the number, nothing more

**Comment by yncyrydybyl** [comment]
I think using € as default for the mifaz connector is good.
Extraction from some textfields is not needed.

**Comment by merlinro** [comment]
done
